server:
  port: 9527
spring:
  application:
    name: cloud-gateway-app
  cloud:
    gateway:
      #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      discovery:
        locator:
          enabled: true
      routes:
        # payment_routh 路由ID ， 没有固定的规则但是要求唯一，建议配合服务名
        - id: payment_routh
          # 匹配提供服务的路由地址
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**
            - After=2020-03-15T16:38:12.202+08:00[Asia/Shanghai]    #在此时间之后可以访问
#            - Between=
#            - Before=
#            - Cookie=username,zzcc                #带cookie访问
#            - Header=Request-id, \d+              #请求头须带Request-id属性，且值为整数
#            - Host=**.zz.com                        #主机名
#            - Query=username, \d+                   #带参数名为usernam,值为整数（正则表达式）
#            - Method=GET                           #get方法允许访问


        # payment_routh 路由ID ， 没有固定的规则但是要求唯一，建议配合服务名
        - id: payment_routh2
          # 匹配提供服务的路由地址
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            # 断言，路径相匹配的进行路由
            - Path=/payment/discovery



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    hostname: cloud-gateway-service
    instance-id: cloud-gateway-service
    prefer-ip-address: true